### PR TITLE
feat!: add support for Jellyfin media

### PR DESCRIPTION
**Pull request by chrisbenincasa**
This commit includes a huge amount of changes, including support for
adding Jellyfin servers as media sources and streaming content from
them.

These are breaking changes and touch almost every corner of the code,
but also pave the way for a lot more flexibility on the backend for
addinng different sources.

The commit also includes performance improvements to the inline modal,
lots of code cleanup, and a few bug fixes I found along the way.

If you are using Tunarr for streaming Plex at version <=0.7.0, it is *highly recommended* to make a backup before upgrading to this version. The DBs are not backwards compatible and it is possible there are breaking bugs here, considering the size of this change. Make a backup so you can revert to 0.7.0 if something goes wrong!

Fixes https://github.com/chrisbenincasa/tunarr/issues/24

### CODE REVIEW

**Comment by RealBradCool** [comment]
hold on maybe try working on a sportts channeel maker

**Comment by RealBradCool** [comment]
also why says draft

**Comment by chrisbenincasa** [comment]
Because it is not done or ready.

**Comment by perkmi** [comment]
Leaving this note for anyone else that may find it useful: In Docker (at least for me) the breaking changes for this commit were resolved by deleting "stream-cache.json" and re-adding the media to my channels. I don't have any watermarks or FLEX media on my channels so I can't speak to those. Since the releases page just says "Breaking Changes" I wasn't sure what to expect, but it's relatively minor. Thanks @chrisbenincasa for all your hard work!

**Comment by chrisbenincasa** [comment]
Appreciate the note @perkmi! I hadn't seen anything like that in my testing, especially with the stream-cache, but it's hard to cover all scenarios. Do you happen to have any logs from when you were having issues? It would be awesome to see if I could make the transition smoother.

**Comment by perkmi** [comment]
[tunarr.log](https://github.com/user-attachments/files/16743089/tunarr.log)

Here's the relevant porion of the log.

I didn't do too much troubleshooting so when I saw the error related to "stream-cache.json" I just blew it away and restarted the container. For all I know it could have resolved itself eventually. It didn't prevent tunarr from starting or anything like that.

I'm guessing all the "Was unable to convert lineup item to guide item" messages were related to the channel media. The channels would show the correct "# Programs" on the "Channels" page, but when I clicked on them the "Channels > Programming" were blank. Re-adding the media to the channels sorted that issue out.

**Comment by chrisbenincasa** [comment]
Hmm interesting, thanks for the logs. I wonder if something went wrong with the DB migration that was required for this change. That is really the only breaking change. The "Was unable to convert lineup item to guide item" log can happen for a lot of reasons, but generally it will happen if the guide builder cannot locate a program with a given ID in the database. This would explain why all of the programming was missing in your channels as well. 

I can look deeper tomorrow. I'm not sure where the migration might've went wrong there, since the changes to the programs table are pretty straightforward ...

**Comment by chrisbenincasa** [comment]
I think I have isolated the problem. It seems to be an issue with the DB migration and the foreign key constraints between the programs and channel_programs table. I have a fix in the works. Sorry you had to recreate your channels!

**Comment by perkmi** [comment]
> I think I have isolated the problem. It seems to be an issue with the DB migration and the foreign key constraints between the programs and channel_programs table. I have a fix in the works. Sorry you had to recreate your channels!

Great! and no worries, I spend more time tinkering than watching anyway.

**Pull request merged**
